(function(){
var f=!0,k=null,l=!1;Array.prototype.indexOf||(Array.prototype.indexOf=function(a,c){var d=this.length,b=Number(c)||0,b=0>b?Math.ceil(b):Math.floor(b);for(0>b&&(b+=d);b<d;b+=1)if(b in this&&this[b]===a)return b;return-1});var m=/BackCompat/i.test(window.document.compatMode)?window.document.body:window.document.documentElement;
function n(){var a={v:0,exist:l,done:l,tag_template:'<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000"codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,0,0"width="{$sWidth}" height="{$sHeight}" style="border:none;padding:0;margin:0"><param name="movie" value="{$sSrc}"><param name="flashvars" value="{$flashVars}"><param name="allowScriptAccess" value="always"><param name="quality" value="autohigh"><param name="bgcolor" value="#fff"><param name="wmode" value="opaque"><embed src="{$sSrc}"flashvars="{$flashVars}"quality="autohigh"allowscriptaccess="always"swliveconnect="FALSE"width="{$sWidth}"height="{$sHeight}"wmode="opaque"type="application/x-shockwave-flash"pluginspage="http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash"></object>'},c=
k;this.p=function(){if(c!==k)return c();if(-1!==window.navigator.userAgent.toLowerCase().indexOf("msie"))try{if("undefined"!==typeof new ActiveXObject("ShockwaveFlash.ShockwaveFlash")){var d=(new ActiveXObject("ShockwaveFlash.ShockwaveFlash")).GetVariable("$version");a.v=parseInt(d.match(/([0-9]+)/)[0],10);a.exist=f}}catch(b){}else"undefined"!==typeof navigator.plugins["Shockwave Flash"]&&(a.v=parseInt(navigator.plugins["Shockwave Flash"].description.match(/\d+\.\d+/),10),a.exist=0!==a.v?f:l);a.done=
f;c=function(){return a};return c()}}
n.prototype={offsetY:function(){var a=k;a===k&&(a="undefined"!==typeof window.scrollY?function(){return Math.max(0,window.scrollY)}:"undefined"!==typeof window.pageYOffset?function(){return Math.max(0,window.pageYOffset)}:function(){return Math.max(0,m.scrollTop)});return a()},offsetX:function(){var a=k;a===k&&(a="undefined"!==typeof window.scrollX?function(){return Math.max(0,window.scrollX)}:"undefined"!==typeof window.pageXOffset?function(){return Math.max(0,window.pageXOffset)}:function(){return Math.max(0,
m.scrollLeft)});return a()}};function q(a,c,d){"undefined"!==typeof a.addEventListener?a.addEventListener(c,d,f):"undefined"!==typeof a.attachEvent&&a.attachEvent("on"+c,d)}function r(a,c){return"undefined"===typeof a[c]?k:a[c]}function s(a,c){a.style.opacity=c;a.style.filter="alpha(opacity="+100*c+")"}function t(a){switch(a){case 1:return"_blank";case 2:return"_top";default:return"_top"}}
function u(a){a=a.match(/\\u[0-9a-fA-F]{4}/g);var c="";if(a===k)return"";for(var d=0;d<a.length;d+=1)c+=String.fromCharCode(a[d].replace("\\u","0x"));return c}function v(a,c){return"script"===c.nodeName.toLowerCase()?c:v(a,c.lastChild)}function w(a){return window.document.getElementById(a)}function x(a){return window.document.createElement(a)}function y(){var a=k;a===k&&(a=function(){return Math.max(m.clientWidth,m.scrollWidth)});return a()}
function z(){var a=k;a===k&&(a="undefined"!==typeof window.innerWidth?function(){return window.innerWidth}:function(){return m.clientWidth});return a()}function A(){var a=k;a===k&&(a="undefined"!==typeof window.innerHeight?function(){return window.innerHeight}:function(){return m.clientHeight});return a()}
if("undefined"===typeof window.adingoFluct){var B=function(){this.c=new n;this.data={};this.g=[];this.h=[];this.b=k;this.d=l;this.e=k;this.u=l;this.a={};this.f=k;this.n=l;this.r={};this.l=l};B.prototype={m:function(a){var c={};c.tag=v(this.c,a);a=c.tag.src;if(!(0>a.indexOf("?"))){a=a.substring(a.indexOf("?")+1);for(var d=a.split("&"),b=d.length,e=0;e<b;e+=1){var g=d[e].split("=");c[g[0]]=g[1]}c.requestQuery=a}this.data[c.G]=c;this.data[c.G].load_status=0},o:function(a){if("success"===a.status){var c=
w("fluctAdLoader_"+a.G);c.parentNode.removeChild(c);var d=this.data[a.G];d.load_status=2;d.json=a;c=this.g.slice(0);this.g=[];if(0<c.length){if(this.n===l){var b=c.shift(),d=d.tag.src.match(/(.+)\/[^\/]+\.js\?.+/)[1]+"/../../cookie_sync.js?";a=a.syncs;var e=[],g;for(g in a)e.push(g+"="+a[g]);g=d+e.join("&");a=window.document.createElement("script");a.setAttribute("src",g);window.document.body.appendChild(a);this.j(b);this.n=f}for(;0<c.length;)b=c.shift(),b!==k&&this.j(b)}}var b=c=0,h;for(h in this.data)c+=
1,2===this.data[h].load_status&&(b+=1);c===b&&(this.h=[])},s:function(a,c){var d=r(this.data[a],"rate");if(d===k||0>=parseInt(d,10))d=60;this.f=setTimeout(function(){window.adingoFluct.reload(a,c)},1E3*d)},reload:function(a,c){this.f!==k&&(clearTimeout(this.f),this.f=k);this.data[a].load_status=B.NONE;this.g.push(c);this.load(a)},load:function(a){var c=k,d=this.data[a],c="undefined"!==typeof d.url?d.url:"http://sh.adingo.jp/api/json/v1/?";d.load_status=1;var b=c=c+d.requestQuery+"&cb=adingoFluct.callback&ttl="+
Math.random(),c=x("script");c.setAttribute("id","fluctAdLoader_"+a);c.src=b;a=d.tag;a.parentNode.insertBefore(c,a.nextSibling)},j:function(a){var c=k;if(-1===this.h.indexOf(a)){var d=w("adingoFluctUnit_"+a);if(d===k){d=x("div");d.setAttribute("id","adingoFluctUnit_"+a);var b=v(this.c,window.document);b.parentNode.insertBefore(d,b.nextSibling)}for(var e in this.data)if(d=this.data[e],"undefined"!==typeof d.load_status&&2===d.load_status)for(b=0;b<d.json.num;b+=1){var g=d.json.ads[b];if(String(g.unit_id)===
a){c=[e,g];break}}else-1===this.h.indexOf(a)&&this.g.push(a),0===d.load_status&&this.load(e);c!==k&&(this.h.push(a),this.q(c))}},q:function(a){var c=a.shift();a=a.shift();var d="adingoFluctUnit_"+a.unit_id,b=a.unit_id,e=w("adingoFluctUnit_"+b),b=w("adingoFluctOverlay_"+b);if(b===k)for(;e.firstChild;)e.removeChild(e.firstChild);else for(;b.firstChild;)b.removeChild(b.firstChild);var g=k;if(1===a.overlay){var e=w("adingoFluctUnit_"+a.unit_id),b=x("div"),h=a.height+"px",p=a.width+"px";b.setAttribute("id",
"adingoFluctOverlay_"+a.unit_id);b.setAttribute("class","adingoFluctOverlay");b.setAttribute("style","width:"+p+";height:"+h+";bottom:0px;left:0px;position:absolute;z-index:9993;display:none;font-size:18px;line-height:1.5em;visibility:visible;opacity:0;verticalAlign:middle;padding:0px;margin:0px;border:none;overflow: hidden;");e.appendChild(b);e="adingoFluctOverlay_"+a.unit_id}else e=d;g=e;switch(a.creative_type){case "html":var e=w(g),b="adingoFluctIframe_"+a.unit_id,h=a.width+"px",p=a.height+"px",
j=x("iframe"),C="0px";1===r(a,"overlay")&&(C="-4px");j.setAttribute("id",b);j.setAttribute("style","width:"+h+";height:"+p+";border:none;padding:0;margin:0;margin-bottom:"+C+";pointer-events:auto;");j.setAttribute("marginwidth",0);j.setAttribute("marginheight",0);j.setAttribute("allowtransparency","false");j.setAttribute("vspace",0);j.setAttribute("hspace",0);j.setAttribute("frameborder",0);j.setAttribute("scrolling","no");e.appendChild(j);e=j.contentWindow.document;e.open();e.write('<html><head></head><body style="padding:0px;margin:0px;border:none;">'+
a.html+"</body></html>");e.close();break;case "flash":e=g;b=this.c.p();e=w(e);b.exist&&5<b.v?(h="clickTAG="+escape(a.landing_url)+"&targetTAG="+t(a.open),b=b.tag_template.replace(/\{\$sWidth\}/g,a.width),b=b.replace(/\{\$sHeight\}/g,a.height),b=b.replace(/\{\$sSrc\}/g,a.creative_url),b=b.replace(/\{\$flashVars\}/g,h),e.innerHTML=b):a.alt_mage!==k&&""!==a.alt_mage&&(b=x("img"),b.setAttribute("src",a.alt_image),b.setAttribute("width",a.width),b.setAttribute("height",a.height),b.setAttribute("border",
0),b.setAttribute("style","border:none;padding:0;margin:0;"),0<a.alt.length&&b.setAttribute("alt",u(a.alt)),h=x("a"),h.setAttribute("href",a.landing_url),h.setAttribute("target",t(a.open)),e.appendChild(h),h.appendChild(b));break;case "image":e=w(g),b=x("img"),b.setAttribute("src",a.creative_url),b.setAttribute("width",a.width),b.setAttribute("height",a.height),b.setAttribute("border",0),b.setAttribute("style","border:none;padding:0;margin:0;"),0<a.alt.length&&b.setAttribute("alt",u(a.alt)),h=x("a"),
h.setAttribute("href",a.landing_url),h.setAttribute("target",t(a.open)),e.appendChild(h),h.appendChild(b)}1===a.overlay&&(this.i(g,500),this.l===l&&(q(window.document,"touchstart",function(a){window.adingoFluct.k(a)}),q(window,"resize",function(a){window.adingoFluct.k(a)}),this.e=setTimeout(function(){window.adingoFluct.move(g)},100),this.l=f));d=w(d);e=a.beacon;b=window.document.createElement("img");b.setAttribute("src",e);b.setAttribute("style","display:none;position:absolute;border:none;padding:0;margin:0;");
b.setAttribute("width",0);b.setAttribute("height",0);b.setAttribute("border",0);d.appendChild(b);1===r(a,"reload")&&(this.r[c]=a,this.s(c,a.unit_id))},k:function(a){if(a.srcElement.offsetParent===k||"undefined"===typeof a.srcElement.offsetParent||"undefined"===typeof a.srcElement.offsetParent.className||"adingoFluctOverlay"!==a.srcElement.offsetParent.className){this.b!==k&&(this.d===l?(clearTimeout(this.b),this.b=k):(clearTimeout(this.b),this.b=k,this.d=l));for(var c in this.a)this.i(c,1E3)}},t:function(){for(var a in this.a)this.i(a,
1E3)},i:function(a,c){this.a[a]={};this.a[a].winPosX=this.c.offsetX();this.a[a].winPosY=this.c.offsetY();this.a[a].winH=A();if(!this.d&&!(A()<z())){this.d=f;var d=w(a);d.style.display="block";var b,e=this.c,g=parseInt(d.style.width,10),h=parseInt(d.style.height,10);b=""!==m.style.zoom?g*m.style.zoom:z()>y()?z()>=g?y()/z():y()/g:z()===y()?1:z()>=g?1:z()/g;var p=""===m.style.zoom?1:m.style.zoom,j=Math.max(0,e.offsetY()),e=e.offsetX(),g=(z()-g*p*b)/p/b/2+e/p/b,h=(j+A()-h*p*b)/p/b,p=j/p/b;if(e=0<j)j+=
A(),e=k,e===k&&(e=function(){return Math.max(m.clientHeight,m.scrollHeight)}),e=e(),e=j>=e-4;e&&(h=p);b={x:g,y:h,zoom:b};j=Math.max(0,b.x)+"px";g=b.y+"px";d.style.zoom=b.zoom;s(d,0);d.style.top=g;d.style.left=j;d=k;this.b=setTimeout(function(){window.adingoFluct.show(a,0)},c)}},show:function(a,c){clearTimeout(this.b);this.b=k;var d=w(a);c+=0.09;s(d,c);d=k;1>=c?this.b=setTimeout(function(){window.adingoFluct.show(a,c)},24):this.d=l},move:function(a){var c=l;if(r(this.a,a)!==k){var d=this.a[a].winPosY,
b=this.a[a].winH;if(this.a[a].winPosX!==this.c.offsetX()||d!==this.c.offsetY()||b!==A())c=f;A()<z()?s(w(a),0):c&&(s(w(a),0),this.a[a].winPosX=this.c.offsetX(),this.a[a].winPosY=this.c.offsetY(),this.a[a].winH=A(),this.b!==k&&(clearTimeout(this.b),this.b=k,this.d!==l&&(this.d=l)),this.i(a,500))}clearTimeout(this.e);this.e=k;this.e=setTimeout(function(){window.adingoFluct.move(a)},100)}};B.prototype.showAd=B.prototype.j;B.prototype.callback=B.prototype.o;B.prototype.setGroup=B.prototype.m;B.prototype.touchHandler=
B.prototype.k;B.prototype.resizeHandler=B.prototype.t;window.adingoFluct=new B}window.adingoFluct.m(window.document);
}());
