(function(){
var e=!0,k=null,l=!1;Array.prototype.indexOf||(Array.prototype.indexOf=function(a,b){var d=this.length,c=Number(b)||0,c=0>c?Math.ceil(c):Math.floor(c);for(0>c&&(c+=d);c<d;c+=1)if(c in this&&this[c]===a)return c;return-1});var m=/BackCompat/i.test(window.document.compatMode)?window.document.body:window.document.documentElement;
function n(){var a={v:0,exist:l,done:l,tag_template:'<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000"codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,0,0"width="{$sWidth}" height="{$sHeight}" style="border:none;padding:0;margin:0"><param name="movie" value="{$sSrc}"><param name="flashvars" value="{$flashVars}"><param name="allowScriptAccess" value="always"><param name="quality" value="autohigh"><param name="bgcolor" value="#fff"><param name="wmode" value="opaque"><embed src="{$sSrc}"flashvars="{$flashVars}"quality="autohigh"allowscriptaccess="always"swliveconnect="FALSE"width="{$sWidth}"height="{$sHeight}"wmode="opaque"type="application/x-shockwave-flash"pluginspage="http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash"></object>'},b=
k;this.p=function(){if(b!==k)return b();if(-1!==window.navigator.userAgent.toLowerCase().indexOf("msie"))try{if("undefined"!==typeof new ActiveXObject("ShockwaveFlash.ShockwaveFlash")){var d=(new ActiveXObject("ShockwaveFlash.ShockwaveFlash")).GetVariable("$version");a.v=parseInt(d.match(/([0-9]+)/)[0],10);a.exist=e}}catch(c){}else"undefined"!==typeof navigator.plugins["Shockwave Flash"]&&(a.v=parseInt(navigator.plugins["Shockwave Flash"].description.match(/\d+\.\d+/),10),a.exist=0!==a.v?e:l);a.done=
e;b=function(){return a};return b()}}
n.prototype={offsetY:function(){var a=k;a===k&&(a="undefined"!==typeof window.scrollY?function(){return Math.max(0,window.scrollY)}:"undefined"!==typeof window.pageYOffset?function(){return Math.max(0,window.pageYOffset)}:function(){return Math.max(0,m.scrollTop)});return a()},offsetX:function(){var a=k;a===k&&(a="undefined"!==typeof window.scrollX?function(){return Math.max(0,window.scrollX)}:"undefined"!==typeof window.pageXOffset?function(){return Math.max(0,window.pageXOffset)}:function(){return Math.max(0,
m.scrollLeft)});return a()}};function q(a,b,d){"undefined"!==typeof a.addEventListener?a.addEventListener(b,d,e):"undefined"!==typeof a.attachEvent&&a.attachEvent("on"+b,d)}function r(a,b){return"undefined"===typeof a[b]?k:a[b]}function s(a,b){a.style.opacity=b;a.style.filter="alpha(opacity="+100*b+")"}function t(a){switch(a){case 1:return"_blank";case 2:return"_top";default:return"_top"}}
function u(a){a=a.match(/\\u[0-9a-fA-F]{4}/g);var b="";if(a===k)return"";for(var d=0;d<a.length;d+=1)b+=String.fromCharCode(a[d].replace("\\u","0x"));return b}function v(a,b){return"script"===b.nodeName.toLowerCase()?b:v(a,b.lastChild)}function w(a){return window.document.getElementById(a)}function x(a){return window.document.createElement(a)}
function y(a){var b=window.document.createElement("img");b.setAttribute("src",a);b.setAttribute("style","display:none;position:absolute;border:none;padding:0;margin:0;");b.setAttribute("width",0);b.setAttribute("height",0);b.setAttribute("border",0);return b}function z(){var a=k;a===k&&(a=function(){return Math.max(m.clientWidth,m.scrollWidth)});return a()}
function A(){var a=k;a===k&&(a="undefined"!==typeof window.innerWidth?function(){return window.innerWidth}:function(){return m.clientWidth});return a()}function B(){var a=k;a===k&&(a="undefined"!==typeof window.innerHeight?function(){return window.innerHeight}:function(){return m.clientHeight});return a()}function C(){}
C.logly=function(){var a="",b=window.document.referrer;try{a=window.parent.document.referrer}catch(d){}try{b=window.parent.document.URL}catch(c){}return y(("https:"===window.document.location.protocol?"https://":"http://")+"dsp.logly.co.jp/sg.gif?"+("sid=1&aid=$luid&url="+escape(b)+"&rurl="+escape(a)))};C.scaleout=function(){return y("http://bid.socdm.com/rtb/sync?proto=adingo&sspid=adingo&tp="+encodeURIComponent(window.document.location.href)+"&pp="+encodeURIComponent(window.document.referrer)+"&t=.gif")};
C.fout=function(){return y("http://sync.fout.jp/sync?xid=fluct")};C.t=function(a,b,d){for(var c in d)"logly"===c?b.parentNode.insertBefore(C[c](a,d[c]),b):b.parentNode.insertBefore(C[c](a),b)};
if("undefined"===typeof window.adingoFluct){var D=function(){this.b=new n;this.data={};this.h=[];this.i=[];this.a=k;this.d=l;this.f=k;this.w=l;this.c={};this.g=k;this.n=l;this.r={};this.l=l};D.prototype={m:function(a){var b={};b.tag=v(this.b,a);a=b.tag.src;if(!(0>a.indexOf("?"))){a=a.substring(a.indexOf("?")+1);for(var d=a.split("&"),c=d.length,f=0;f<c;f+=1){var g=d[f].split("=");b[g[0]]=g[1]}b.requestQuery=a}this.data[b.G]=b;this.data[b.G].load_status=0},o:function(a){if("success"===a.status){var b=
w("fluctAdLoader_"+a.G);b.parentNode.removeChild(b);b=this.data[a.G];b.load_status=2;b.json=a;b=this.h.slice(0);this.h=[];if(0<b.length){if(this.n===l){var d=b.shift();C.t(this.b,w("adingoFluctUnit_"+d),a.syncs);this.k(d);this.n=e}for(;0<b.length;)a=b.shift(),a!==k&&this.k(a)}}var b=a=0,c;for(c in this.data)a+=1,2===this.data[c].load_status&&(b+=1);a===b&&(this.i=[])},s:function(a,b){var d=r(this.data[a],"rate");if(d===k||0>=parseInt(d,10))d=60;this.g=setTimeout(function(){window.adingoFluct.reload(a,
b)},1E3*d)},reload:function(a,b){this.g!==k&&(clearTimeout(this.g),this.g=k);this.data[a].load_status=D.NONE;this.h.push(b);this.load(a)},load:function(a){var b=k,d=this.data[a],b="undefined"!==typeof d.url?d.url:"http://y-nomura.sh.adingo.jp.dev.fluct.me/api/json/v1/?";d.load_status=1;var c=b=b+d.requestQuery+"&cb=adingoFluct.callback&ttl="+Math.random(),b=x("script");b.setAttribute("id","fluctAdLoader_"+a);b.src=c;a=d.tag;a.parentNode.insertBefore(b,a.nextSibling)},k:function(a){var b=k;if(-1===
this.i.indexOf(a)){var d=w("adingoFluctUnit_"+a);if(d===k){d=x("div");d.setAttribute("id","adingoFluctUnit_"+a);var c=v(this.b,window.document);c.parentNode.insertBefore(d,c.nextSibling)}for(var f in this.data)if(d=this.data[f],"undefined"!==typeof d.load_status&&2===d.load_status)for(c=0;c<d.json.num;c+=1){var g=d.json.ads[c];if(String(g.unit_id)===a){b=[f,g];break}}else-1===this.i.indexOf(a)&&this.h.push(a),0===d.load_status&&this.load(f);b!==k&&(this.i.push(a),this.q(b))}},q:function(a){var b=
a.shift();a=a.shift();var d="adingoFluctUnit_"+a.unit_id,c=a.unit_id,f=w("adingoFluctUnit_"+c),c=w("adingoFluctOverlay_"+c);if(c===k)for(;f.firstChild;)f.removeChild(f.firstChild);else for(;c.firstChild;)c.removeChild(c.firstChild);var g=k;if(1===a.overlay){var f=w("adingoFluctUnit_"+a.unit_id),c=x("div"),h=a.height+"px",p=a.width+"px";c.setAttribute("id","adingoFluctOverlay_"+a.unit_id);c.setAttribute("class","adingoFluctOverlay");c.setAttribute("style","width:"+p+";height:"+h+";bottom:0px;left:0px;position:absolute;z-index:9993;display:none;font-size:18px;line-height:1.5em;visibility:visible;opacity:0;verticalAlign:middle;padding:0px;margin:0px;border:none;overflow: hidden;");
f.appendChild(c);f="adingoFluctOverlay_"+a.unit_id}else f=d;g=f;switch(a.creative_type){case "html":var f=w(g),c="adingoFluctIframe_"+a.unit_id,h=a.width+"px",p=a.height+"px",j=x("iframe"),E="0px";1===r(a,"overlay")&&(E="-4px");j.setAttribute("id",c);j.setAttribute("style","width:"+h+";height:"+p+";border:none;padding:0;margin:0;margin-bottom:"+E+";pointer-events:auto;");j.setAttribute("marginwidth",0);j.setAttribute("marginheight",0);j.setAttribute("allowtransparency","false");j.setAttribute("vspace",
0);j.setAttribute("hspace",0);j.setAttribute("frameborder",0);j.setAttribute("scrolling","no");f.appendChild(j);f=j.contentWindow.document;f.open();f.write('<html><head></head><body style="padding:0px;margin:0px;border:none;">'+a.html+"</body></html>");f.close();break;case "flash":f=g;c=this.b.p();f=w(f);c.exist&&5<c.v?(h="clickTAG="+escape(a.landing_url)+"&targetTAG="+t(a.open),c=c.tag_template.replace(/\{\$sWidth\}/g,a.width),c=c.replace(/\{\$sHeight\}/g,a.height),c=c.replace(/\{\$sSrc\}/g,a.creative_url),
c=c.replace(/\{\$flashVars\}/g,h),f.innerHTML=c):a.alt_mage!==k&&""!==a.alt_mage&&(c=x("img"),c.setAttribute("src",a.alt_image),c.setAttribute("width",a.width),c.setAttribute("height",a.height),c.setAttribute("border",0),c.setAttribute("style","border:none;padding:0;margin:0;"),0<a.alt.length&&c.setAttribute("alt",u(a.alt)),h=x("a"),h.setAttribute("href",a.landing_url),h.setAttribute("target",t(a.open)),f.appendChild(h),h.appendChild(c));break;case "image":f=w(g),c=x("img"),c.setAttribute("src",a.creative_url),
c.setAttribute("width",a.width),c.setAttribute("height",a.height),c.setAttribute("border",0),c.setAttribute("style","border:none;padding:0;margin:0;"),0<a.alt.length&&c.setAttribute("alt",u(a.alt)),h=x("a"),h.setAttribute("href",a.landing_url),h.setAttribute("target",t(a.open)),f.appendChild(h),h.appendChild(c)}1===a.overlay&&(console.log("ava"),this.j(g,500),this.l===l&&(q(window.document,"touchstart",function(a){window.adingoFluct.e(a)}),q(window,"resize",function(a){window.adingoFluct.e(a)}),q(window,
"orientationchange",function(a){window.adingoFluct.e(a)}),q(window.document,"touchmove",function(a){window.adingoFluct.e(a)}),this.f=setTimeout(function(){window.adingoFluct.move(g)},100),this.l=e,console.log("ddododo")));d=w(d);f=y(a.beacon);d.appendChild(f);1===r(a,"reload")&&(this.r[b]=a,this.s(b,a.unit_id))},e:function(a){if(a.srcElement.offsetParent===k||"undefined"===typeof a.srcElement.offsetParent||"adingoFluctOverlay"!==a.srcElement.offsetParent.className){this.a!==k&&(this.d===l?(clearTimeout(this.a),
this.a=k):(clearTimeout(this.a),this.a=k,this.d=l));for(var b in this.c)this.j(b,1E3)}},u:function(){for(var a in this.c)this.j(a,1E3)},j:function(a,b){if(!this.d&&!(B()<A())){this.d=e;var d=w(a);d.style.display="block";var c,f=this.b,g=parseInt(d.style.width,10),h=parseInt(d.style.height,10);c=""!==m.style.zoom?g*m.style.zoom:A()>z()?A()>=g?z()/A():z()/g:1;var p=""===m.style.zoom?1:m.style.zoom,j=f.offsetY(),f=f.offsetX(),g=(A()-g*p*c)/p/c/2+f,h=(j+B()-h*p*c)/p/c;c={x:g,y:h,top:j/p/c,zoom:c};p=Math.max(0,
c.x)+"px";j=c.y+"px";if(h=0<this.b.offsetY())h=this.b.offsetY()+B(),g=k,g===k&&(g=function(){return Math.max(m.clientHeight,m.scrollHeight)}),g=g(),h=h>=g;h&&(j=c.top+"px");d.style.zoom=c.zoom;s(d,0);d.style.top=j;d.style.left=p;d=k;this.c[a]={};this.c[a].winPosX=this.b.offsetX();this.c[a].winPosY=this.b.offsetY();console.log("avava");this.a=setTimeout(function(){window.adingoFluct.show(a,0)},b)}},show:function(a,b){clearTimeout(this.a);this.a=k;var d=w(a);b+=0.09;s(d,b);d=k;1>=b?this.a=setTimeout(function(){window.adingoFluct.show(a,
b)},24):this.d=l},move:function(a){var b=l;if(r(this.c,a)===k)console.log("gdggaaga");else{var d=this.c[a].winPosY;if(this.c[a].winPosX!==this.b.offsetX()||d!==this.b.offsetY())b=e;B()<A()?s(w(a),0):b&&(s(w(a),0),this.c[a].winPosX=this.b.offsetX(),this.c[a].winPosY=this.b.offsetY(),this.a!==k&&(this.d===l?(clearTimeout(this.a),this.a=k):(clearTimeout(this.a),this.a=k,this.d=l)),this.j(a,500))}clearTimeout(this.f);this.f=k;this.f=setTimeout(function(){window.adingoFluct.move(a)},100)}};D.prototype.showAd=
D.prototype.k;D.prototype.callback=D.prototype.o;D.prototype.setGroup=D.prototype.m;D.prototype.touchHandler=D.prototype.e;D.prototype.resizeHandler=D.prototype.u;window.adingoFluct=new D}window.adingoFluct.m(window.document);
}());
